### ISSUE TITLE
Build MCUboot as a RIOT app

### ISSUE THREAD

**Issue by aditihilbert** [JuulLabs-OSS/mcuboot#208]
https://runtimeco.atlassian.net/browse/MCUB-72

Francisco Acosta added a comment - 05/Dec/17 7:15 AM:
For 1.1 release I'll add just a "small" update on which RIOT will include a signature using the example key (the one on the mcuboot git repo). A pre-compiled mynewt mcuboot binary with signature and hash checks enabled will be used to boot this new RIOT image.

**Comment by d3zd3z** [comment]
Is this still a desired feature? Please feel free to reopen if this needs to be considered.
