### ISSUE TITLE
Support for loading image from Flash into on-chip RAM

### ISSUE THREAD

**Issue by aditihilbert** [JuulLabs-OSS/mcuboot#215]
The boot loader should support the option where slot 1 is defined in external flash. The new image needs to be uploaded to on-chip flash/RAM (slot 0). 
Swap space can be defined by the user in the external flash. This allows fall back to known good image in case the new image fails to boot.
-----------------------
David Brown added a comment - 22/Aug/17 2:18 PM
One point of complexity here has to do with the minimum write size. If they differ between the external and internal flash, we would have to probably pick the largest value. At least this will have to be accounted for in the software.

**Comment by d3zd3z** [comment]
Is this implemented?

**Comment by d3zd3z** [comment]
Also, is the subject correct, or is this just about supporting external and internal flash?

**Comment by aditihilbert** [comment]
this is done.
