### ISSUE TITLE
Add SHA-512 capability to MCUBoot

### ISSUE THREAD

**Issue by aditihilbert** [JuulLabs-OSS/mcuboot#222]
Digest size is 512 bit, hash function computed with 64-bit words. 
tweetnacl supports only this hash function. 

A new type is needed to support it. 
Should be a config variable for the user to choose if desired. 

Also needs support to 'newt' 'imgtool' and 'imgtool.py' for this new hash.
Options

**Comment by d3zd3z** [comment]
Now that we've added ed25519 support using a different library than tweetnacl, do we still need this issue. I'll close it for now.
