### ISSUE TITLE
How the boot state exchanges?

### ISSUE THREAD

**Issue by BabaYB** [JuulLabs-OSS/mcuboot#319]
I have some questions about the state exchanging.    
First, is it right in the picture of the state exchanging when we download a new image and set the magic of SLOT1?    
So what will the next boot be?    
And if we set the image_ok in SLOT1 when the new app is running?Then the next boot will determines the state as BOOT_SWAP_TYPE_PERM, and swaping the old image in SLOT1 back to SLOT0?    
So the second is when shall we set and use the `boot_set_pending()`?   
![table](https://user-images.githubusercontent.com/16234146/43119272-54261f22-8f48-11e8-9182-25c9de1787f2.png)

**Comment by BabaYB** [comment]
It would be better if there is a map of the state exchanging.

**Comment by d3zd3z** [comment]
There have been quite a few updates to `docs/design.md`. Is your question answered there. If not, it would probably be best to answer this with a doc update.

**Comment by d3zd3z** [comment]
Closing. Please open if there are aspects of this not described in the design doc.
