### ISSUE TITLE
https://mcuboot.com/ is down

### ISSUE THREAD

**Issue by mbolivar** [JuulLabs-OSS/mcuboot#358]
This appears to be a result of the move to the new location.

Or are DNS records just taking a while to update?

**Comment by utzig** [comment]
It is currently back, but might be down again while trying to restore the same configuration as was before.

**Comment by utzig** [comment]
What I **think** is happening is that Cloudfront, which we use to provide `SSL`, is somehow pointing to `runtimeco.github.io/mcuboot` and needs to be updated to point to `JuulLabs-OSS.github.io/mcuboot`. Not really sure, and I never had to setup cloudfront, so I'll check out with the admin when he's online.

**Comment by spoonofpower** [comment]
CloudFront configs were updated to point to the new repo location and mcuboot.com availability was restored on Thu Nov 15 at 9:35 PM PST.

**Comment by mbolivar** [comment]
Thanks!
