### ISSUE TITLE
building bootloader

### ISSUE THREAD

**Issue by jrananth1032** [JuulLabs-OSS/mcuboot#361]
when i'm trying to build bootloader it shows the error as "DT_FLASH_DEV_NAME" is not defind.
i am new to this mcuboot and i have to work on mcumgr also. so kindly help me on this.

**Comment by utzig** [comment]
You need to update Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/11180

**Comment by jrananth1032** [comment]
i'm using the latest zephyr v1.13
  1 VERSION_MAJOR = 1
  2 VERSION_MINOR = 13
  3 PATCH_LEVEL = 0
  4 VERSION_TWEAK = 0
  5 EXTRA_VERSION = rc3
and still facing the problem as 
‘DT_FLASH_DEV_NAME’  undeclared

**Comment by jrananth1032** [comment]
thank you for your solution that problem is solved.
