### ISSUE TITLE
#if used for MCUBOOT_OVERWRITE_ONLY where #ifdef is needed

### ISSUE THREAD

**Issue by kzyapkov** [JuulLabs-OSS/mcuboot#384]
338a19f70d696d9f3 adds two lines with `#if MCUBOOT_OVERWRITE_ONLY` but they should probably be `#ifdef MCUBOOT_OVERWRITE_ONLY`

**Comment by utzig** [comment]
@kzyapkov Thanks for catching this!

**Comment by utzig** [comment]
Fixed by #385
