### ISSUE TITLE
${BOARD}.overlay is not being appended when BOARD is set through the environment

### ISSUE THREAD

**Issue by SebastianBoe** [JuulLabs-OSS/mcuboot#400]
The bootloader build scripts are trying to append the file "boards/${BOARD}.overlay" to the overlay list when it exists, but it does not work because before boilerplate.cmake is executed the BOARD is not known.

Also, when DTC_OVERLAY_FILE has been specified on the CLI the CACHE argument must be given to 'set' when modifying DTC_OVERLAY_FILE.

**Comment by sigvartmh** [comment]
Guess this is fixed by ea49cd0b1a62a7bb41b9d0fb87e905b291113196 so close the issue?

**Comment by SebastianBoe** [comment]
This is still a valid bug.

On this line we have not run boilerplate.cmake, so we don't know what BOARD is, and therefore can't de-reference it.

https://github.com/JuulLabs-OSS/mcuboot/blob/master/boot/zephyr/CMakeLists.txt#L26

**Comment by d3zd3z** [comment]
Now that is a feature supported by the Zephyr cmake files, are we able to close this bug (at least now that #577 has merged). Are we ok to close this issue?

**Comment by SebastianBoe** [comment]
Looks like this is fixed, yes :)
