### ISSUE TITLE
Zephyr: assemble.py relies on generated_dts_board.h

### ISSUE THREAD

**Issue by kzyapkov** [JuulLabs-OSS/mcuboot#408]
With the latest zephyr master branch we get:

    FileNotFoundError: [Errno 2] No such file or directory: '.../mcuboot/zephyr/include/generated/generated_dts_board.h'

It seems https://github.com/zephyrproject-rtos/zephyr/commit/c23cc26c73eb9d6253dd2e51eed5a3c380ff9c9b changes that to `generated_dts_board_unfixed.h`

**Comment by nvlsianpu** [comment]
Compiles fine for me. I'm using nrf52_pca10056. Try clean build.

**Comment by kzyapkov** [comment]
I did try a clean build, with zephyr's latest master.

Trying to build `mcuboot/samples/zephyr/` fails with the same error for me. Note that the breaking change in zephyr only showed up hours ago.

**Comment by bfrog** [comment]
I just hit this myself
