### ISSUE TITLE
Issue with status write fails

### ISSUE THREAD

**Issue by dewalddebruyn** [JuulLabs-OSS/mcuboot#413]
I'm using mcuboot on an STM32L4 with Zephyr. Status writes always fail due to the flash area used for status bits not being erased properly. **The bootloader works but is not robust to power loss during image swapping.**

The flash erase size is 2048 and the write size is 8. With the default CONFIG_BOOT_MAX_IMG_SECTORS = 128, the area required for the image trailer is (3 * 8 * 128 + 3 * 8 + 16) = 3112 bytes, because of "#define BOOT_STATUS_MAX_ENTRIES    BOOT_MAX_IMG_SECTORS"

The problem is that "boot_erase_last_sector_by_id" called to initialize the flash before "boot_status_init_by_id" only erases the last sector (2048 bytes), but for this to work in my application the last two sectors need to be erased. The function does not take into account the actual image trailer size.

I cannot reduce the number of sectors, because I have 224K image slots. It seems to me that BOOT_MAX_IMG_SECTORS is related to flash sectors (2048 bytes), while BOOT_STATUS_MAX_ENTRIES is related to the size of the scratch area. Reducing BOOT_STATUS_MAX_ENTRIES directly in bootutil_priv.h seems to fix the problem.

**Comment by utzig** [comment]
This was fixed by #404

**Comment by dewalddebruyn** [comment]
Thanks, didn't see that. I'll check out the latest version.
