### ISSUE TITLE
MCUBoot is not placed in proper partition - Zephyr nrf52840_pca10059

### ISSUE THREAD

**Issue by MarekPieta** [JuulLabs-OSS/mcuboot#444]
MCUBoot is not placed in mcuboot flash partition on Zephyr nrf52840_pca10059 (tested with default configuration).
It is placed in the beginning of flash even if DTS specifies otherwise (according to current DTS it should be placed after Nordic MBR).

**Comment by utzig** [comment]
Are you using a release or running from `master`? If so what is your latest sha?

**Comment by MarekPieta** [comment]
I'm using MCUBoot from repo: NordicPlayground/fw-nrfconnect-mcuboot
commit sha: 59fde9c792bfaa36887c860fb8cd0ca1f1bc4db5

**Comment by nvlsianpu** [comment]
cc @lemrey

**Comment by lemrey** [comment]
Right, something seems wrong; will open a PR to fix this later today.

**Comment by nvlsianpu** [comment]
Looks like this can be a case for any else target.

**Comment by nvlsianpu** [comment]
fixed via https://github.com/zephyrproject-rtos/zephyr/pull/14620 + #447
