### ISSUE TITLE
imgtool: using public RSA key for signing results with error

### ISSUE THREAD

**Issue by ChristopherBittner** [JuulLabs-OSS/mcuboot#455]
Example: Public RSA2048 key is used as an encryption and signing key.

```
python mcuboot/scripts/imgtool.py sign 
-k mcuboot/enc-rsa2048-pub.pem
 --align 4 --version 0.1.2 --header-size 512 --slot-size 430080 
-E mcuboot/enc-rsa2048-pub.pem 
hello_world_pca10028_hello.hex 
signed.hex
```

Calling above command result with
`  
File "mcuboot/scripts/imgtool/main.py", line 162, in sign
    img.create(key, enckey)
  File "mcuboot/scripts/imgtool/image.py", line 191, in create
    sig = key.sign(bytes(self.payload))
AttributeError: 'RSA2048Public' object has no attribute 'sign'
`

Instead it should be discarded at main.py

Addressed in PR https://github.com/JuulLabs-OSS/mcuboot/pull/454

**Comment by utzig** [comment]
Fixed with #454
