### ISSUE TITLE
How as a user can confirm that the image is OK?

### ISSUE THREAD

**Issue by gon1332** [JuulLabs-OSS/mcuboot#493]
After reading the docs and running the bootloader (with Zephyr), I understood that there is also a user method of marking an image as OK (image trailer specific field). After that, either a permanent swap will be performed, or a revert.

> Image OK: A single byte indicating whether the image in this slot has been confirmed as good by the user (0x01=confirmed; 0xff=not confirmed).

Is there an API I can refer into?

**Comment by utzig** [comment]
You can call `boot_set_confirmed` from your application; it will write `image_ok` to the primary slot:

https://github.com/JuulLabs-OSS/mcuboot/blob/master/boot/bootutil/src/bootutil_misc.c#L684

**Comment by gon1332** [comment]
Moreover for the Zephyr users, the wrapper is [`boot_write_img_confirmed`](https://github.com/zephyrproject-rtos/zephyr/blob/master/include/dfu/mcuboot.h#L145).
