### ISSUE TITLE
Multi-image upgrade with non-satisfied dependencies hangs boot forever

### ISSUE THREAD

**Issue by utzig** [JuulLabs-OSS/mcuboot#518]
When dependency check is done, if the version available is less than the expected version, the checking routines hangs forever. The correct thing to do would be to boot the current version and not try to upgrade.

See: https://github.com/JuulLabs-OSS/mcuboot/blob/master/boot/bootutil/src/loader.c#L1792

**Comment by tamasban** [comment]
Could you elaborate when can this happen:
- The dependencies of original images are satisfied?
- How many image is tried to be upgraded? 1 or 2?
- I assume the new image dependency is not satisfied.
- Does the dependency check restarts forever?

**Comment by d3zd3z** [comment]
@utzig is this fixed now?

**Comment by utzig** [comment]
Yes, was fixed at the same time that dependency testing was added to the simulator.
