### ISSUE TITLE
Code does not check if dependencies are protected

### ISSUE THREAD

**Issue by d3zd3z** [JuulLabs-OSS/mcuboot#538]
Recent code added support for protected TLVs (see diagram below). The intent was that the dependency information would be included in this protected area so that users would not be able to tamper with the dependency information.

However, the code does not check that these dependencies are actually protected. In addition, future work will add a TLV for a rollback counter that also needs to be protected. We probably want some generic code that can traverse the TLV and make sure that certain known TLV entries are always protected, and reject an upgrade if this is not the case.

Related to #539.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/90349/63782193-42a9dc80-c8a8-11e9-99ae-9d6635796a2a.png">

**Comment by utzig** [comment]
> However, the code does not check that these dependencies are actually protected.

This is not entirely true. The code checks dependencies when an upgrade flag was set, and it that case it also runs a validation of the image in the secondary slot (which guarantees the dependency's validity). Now it's possible that it might be skipped in some circumstances (bug!) but it should be working.

**Comment by d3zd3z** [comment]
I'm ok closing this, since it was based on a misunderstanding on my part.
