### ISSUE TITLE
FW update problem

### ISSUE THREAD

**Issue by MarekPieta** [JuulLabs-OSS/mcuboot#553]
I use MCUBoot with 2 image slots on Zephyr device.

I noticed that image verification fails on reboot with image swap (test swap) after overriding image on second partition with image with different size. After failed verification, partition is erased.
On second upload try (after mentioned erase) image verification is successfull and image is swapped.

To override image on second slot with new image data, I use custom code (simply writing content of update binary file from the beginning of secondary partition up to image size in binary file). Rest of image slot remains unchanged. In addition at the end of upload `boot_request_upgrade(false)` function is called.

Is it necessary to erase whole partition when uploading new image? Or I observe some sort of bug?

**Comment by utzig** [comment]
> I noticed that image verification fails on reboot with image swap (test swap) after overriding image on second partition with image with different size. After failed verification, partition is erased.
On second upload try (after mentioned erase) image verification is successfull and image is swapped.

What version are you using? `master`? It would be very helpful if you could describe the exact steps you are doing.

> Is it necessary to erase whole partition when uploading new image? Or I observe some sort of bug?

No, you just need to erase whatever area you're writing the new image to, not the whole slot. When a verification of the image in second slot fails, it is erased, that is normal behaviour. So, it seems we have to find why it is failing verification.

**Comment by MarekPieta** [comment]
I noticed that problem was caused by the fact that part of FLASH was not properly erased by application before write operation (it is why problem was not occurring after erasing whole partition). It is fixed already, so I am closing the issue. Sorry for problems.
