### ISSUE TITLE
Bootstrap does not work when CONFIG_BOOT_SWAP_USING_MOVE=y

### ISSUE THREAD

**Issue by DunderRoffe** [JuulLabs-OSS/mcuboot#706]
I am trying to bootstrap MCUBoot using Slot1 but it does not seem to work when CONFIG_BOOT_SWAP_USING_MOVE=y. 

It seems like it fails on checking the magic for Slot 0. This is expected as there is nothing in Slot0 but I do not understand why it is checked.

Is this a bug in MCUBoot or have I misunderstood how this is supposed to work?
It works fine when CONFIG_BOOT_SWAP_USING_MOVE=n

RTOS: Zephyr
Target board: particle_boron
mcuboot conf:
```
CONFIG_BOOT_BOOTSTRAP=y
CONFIG_BOOT_SWAP_USING_MOVE=y
```

**Comment by erik-johnson-nimbelink** [comment]
I believe I've also come across this. I haven't been able to get bootstrapping to work with this combination.

**Comment by utzig** [comment]
Thanks for reporting, it should have been fixed by #826, feel free to reopen if the issue persists!
