### ISSUE TITLE
boot_write_swap_size() works incorrect with align 1 and/or 2

### ISSUE THREAD

**Issue by BohdanKovalchuk** [JuulLabs-OSS/mcuboot#755]
boot_write_swap_size() API calculates swap_size offset inside boot_swap_size_off();

This one uses BOOT_MAX_ALIGN, which is allowed to be from list of [1, 2, 4, 8].

In case of values 1 and 2 writing swap_size (which length is 4-bytes) will corrupt neighbor values - copy_done, image_ok, magic.

**Comment by utzig** [comment]
> This one uses BOOT_MAX_ALIGN, which is allowed to be from list of [1, 2, 4, 8].

`BOOT_MAX_ALIGN` is fixed at 8: https://github.com/JuulLabs-OSS/mcuboot/blob/master/boot/bootutil/include/bootutil/bootutil.h#L61

**Comment by BohdanKovalchuk** [comment]
Closing, not a defect.
