### ISSUE TITLE
Single-image boot is ambiguous

### ISSUE THREAD

**Issue by davidvincze** [JuulLabs-OSS/mcuboot#800]
The terms "single-image boot" and the "single image application" of Zephyr are confused.
The original suggestion comes from @nvlsianpu (https://github.com/JuulLabs-OSS/mcuboot/pull/793#discussion_r487111576).
It is not clear whether the MCUBoot handles only one updateable image with the "classic" primary + secondary image slot model or there is only 1 image slot in total.
Would it make sense to have this single slot/image mode in case of multiple independent images?
The documentation and comments should be rephrased to clearly distinguish these 2 cases.

**Comment by davidvincze** [comment]
I would rather rename the `MCUBOOT_SINGLE_IMAGE_DFU` option to something like `MCUBOOT_SINGLE_SLOT_DFU`.

**Comment by nvlsianpu** [comment]
@de-nordic What is your opinion? As you are the inventor of single slot DFU.

**Comment by davidvincze** [comment]
It was fixed by: https://github.com/JuulLabs-OSS/mcuboot/pull/801.
I am closing this issue.
