### ISSUE TITLE
Understanding of tag names

### ISSUE THREAD

**Issue by caco3** [JuulLabs-OSS/mcuboot#842]
Is there some explanations to the tags marked with `*-cypress` and `TF-Mv*-integ`?

As far as I can see they are all in the master tree.

Is it wise to use `v1.6.0-cypress` instead `v1.6.0` on a Nordic chip?

I am using Zephyrproject `v2.4.0` and had to switch to `v1.6.0-cypress` because `v1.6.0` misses the required changes https://github.com/JuulLabs-OSS/mcuboot/commit/0813efeac65588cc3895ba71cdc69c88bb946334

Or is it even better to go to the latest tag (currently `TF-Mv1.2-integ`)?

**Comment by utzig** [comment]
Those are unrelated to the Zephyr port, you can use them but there's no special significance for Zephyr users. Or use `master`, or wait a week or so until we tag `1.7.0-something`.

**Comment by caco3** [comment]
Thank you!
